### ISSUE TITLE
报错 "TypeError: Return value of yzh52521\\middleware\\Throttle::handle() must be an instance of support\\Response, instance of Webman\\Http\\Response returned"

### ISSUE THREAD

**Issue by evilk123** [yzh52521/webman-throttle#2]
1.
前两天刚安装的时候,还能正常使用,后来就不可以了

2.
以下是相关信息
PHP version = 7.4.26
workerman/webman-framework version = 1.3.9
workerman version = 4.0.33
yzh52521/webman-throttle version = 1.0.4

3.
Throttle.php : 
```
namespace app\api\middleware;

use Webman\MiddlewareInterface;
use Webman\Http\Response;
use Webman\Http\Request;

/**
 * Class Throttle
 * @package app\api\middleware
 */
class Throttle implements MiddlewareInterface
{
    public function process(Request $request, callable $next, array $params = []): Response
    {
        return (new \yzh52521\middleware\Throttle())->handle($request, $next, $params);
    }
}
```

4.
报错信息如下:
`TypeError: Return value of yzh52521\\middleware\\Throttle::handle() must be an instance of support\\Response, instance of Webman\\Http\\Response returned`

因为`(new \yzh52521\middleware\Throttle())->handle()`返回的是 `support\Response`

很奇怪,刚开始安装的时候,可以使用的

**Comment by yuanzhihai** [comment]
我用的没有问题啊
也是 
workerman/webman-framework version = 1.3.9
workerman version = 4.0.33
yzh52521/webman-throttle version = 1.0.4

support\Response 也是继承 Webman\\Http\\Response

**Comment by yuanzhihai** [comment]
你试一下 改成 Webman\\Http\\Response 这个就不报错了么？

**Comment by evilk123** [comment]
support\Response 也是继承 Webman\Http\Response
是的,按理说,应该不会报错

"你试一下 改成 Webman\Http\Response 这个就不报错了么?"
刚才试了一下,是的

然后
我又改回去了
然后,再重启服务,又好了...
我再多尝试几次
谢谢

**Comment by evilk123** [comment]
找到原因了
我用了自定义exceptionHandler
```
public function render(Request $request, Throwable $throwable): Response
    {
        $message = ErrorCode::getMessageByCode(ErrorCode::ServerError_FrameworkError);

        //如果开启了限流中间件,这里会出现两个(不清楚是哪里抛出的这个TypeError)
        //support\\exception\\ApiException
        //TypeError

        //如果没有开启了限流中间件,这里只会出现1个,这才是正常的
        //support\\exception\\ApiException

        var_export(get_class($throwable));
       
        if (in_array(get_class($throwable), $this->exceptionWhiteMap)) {
            $message = $throwable->getMessage();
        } else {
            $log = [];
            $log['file'] = $throwable->getFile();
            $log['line'] = $throwable->getLine();
            $log['message'] = $throwable->getMessage();
            Log::channel('default')->info(json_encode($log, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        }

        $code = $throwable->getCode();
        $json = ['code' => $code, 'message' => $message];
        $this->_debug && $json['traces'] = (string)$throwable;
        return new Response(200, ['Content-Type' => 'application/json'], json_encode($json, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    }
```
很奇怪
- 我只是请求一次,还没有触发限流
- 我只是抛出了一个自定义异常
- 却会返回一个 `TypeError`
- 不清楚是哪里返回的

**Comment by yuanzhihai** [comment]
你是什么定义异常？
发我看看





------------------ 原始邮件 ------------------
发件人: evilk123 ***@***.***&gt;
发送时间: 2022年4月9日 14:46
收件人: yzh52521/webman-throttle ***@***.***&gt;
抄送: 听风吹雨 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yzh52521/webman-throttle] 报错 "TypeError: Return value of yzh52521\\middleware\\Throttle::handle() must be an instance of support\\Response, instance of Webman\\Http\\Response returned" (Issue #2)





 
找到原因了
 我用了自定义exceptionHandler
 public function render(Request $request, Throwable $throwable): Response     {         $message = ErrorCode::getMessageByCode(ErrorCode::ServerError_FrameworkError);         //如果开启了限流中间件,这里会出现两个(不清楚是哪里抛出的这个TypeError)         //support\\exception\\ApiException         //TypeError         //如果没有开启了限流中间件,这里只会出现1个,这才是正常的         //support\\exception\\ApiException         var_export(get_class($throwable));                 if (in_array(get_class($throwable), $this-&gt;exceptionWhiteMap)) {             $message = $throwable-&gt;getMessage();         } else {             $log = [];             $log['file'] = $throwable-&gt;getFile();             $log['line'] = $throwable-&gt;getLine();             $log['message'] = $throwable-&gt;getMessage();             Log::channel('default')-&gt;info(json_encode($log, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));         }         $code = $throwable-&gt;getCode();         $json = ['code' =&gt; $code, 'message' =&gt; $message];         $this-&gt;_debug &amp;&amp; $json['traces'] = (string)$throwable;         return new Response(200, ['Content-Type' =&gt; 'application/json'], json_encode($json, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));     }  
很奇怪
  
我只是请求一次,还没有触发限流 

我只是抛出了一个自定义异常 

却会返回一个 TypeError 

不清楚是哪里返回的

**Comment by evilk123** [comment]
> 你是什么定义异常？ 发我看看
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: evilk123 ***@***.***&gt; 发送时间: 2022年4月9日 14:46 收件人: yzh52521/webman-throttle ***@***.***&gt; 抄送: 听风吹雨 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [yzh52521/webman-throttle] 报错 "TypeError: Return value of yzh52521\\middleware\\Throttle::handle() must be an instance of support\\Response, instance of Webman\\Http\\Response returned" (Issue #2) 找到原因了 我用了自定义exceptionHandler public function render(Request $request, Throwable $throwable): Response { $message = ErrorCode::getMessageByCode(ErrorCode::ServerError_FrameworkError); //如果开启了限流中间件,这里会出现两个(不清楚是哪里抛出的这个TypeError) //support\\exception\\ApiException //TypeError //如果没有开启了限流中间件,这里只会出现1个,这才是正常的 //support\\exception\\ApiException var_export(get_class($throwable)); if (in_array(get_class($throwable), $this-&gt;exceptionWhiteMap)) { $message = $throwable-&gt;getMessage(); } else { $log = []; $log['file'] = $throwable-&gt;getFile(); $log['line'] = $throwable-&gt;getLine(); $log['message'] = $throwable-&gt;getMessage(); Log::channel('default')-&gt;info(json_encode($log, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)); } $code = $throwable-&gt;getCode(); $json = ['code' =&gt; $code, 'message' =&gt; $message]; $this-&gt;_debug &amp;&amp; $json['traces'] = (string)$throwable; return new Response(200, ['Content-Type' =&gt; 'application/json'], json_encode($json, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)); } 很奇怪 我只是请求一次,还没有触发限流 我只是抛出了一个自定义异常 却会返回一个 TypeError 不清楚是哪里返回的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

![image](https://user-images.githubusercontent.com/16203922/162560516-174cdae5-2ad0-4980-b984-b510613cb4d1.png)

**Comment by evilk123** [comment]
![image](https://user-images.githubusercontent.com/16203922/162560639-2f3666a5-00df-4008-879f-23a722c08c8f.png)

**Comment by evilk123** [comment]
奇怪的是
我抛出的是自定义异常,为啥最后handler还多接收到了另一个`TypeError `
感觉没道理啊

**Comment by evilk123** [comment]
`controller`:
```
public function redeemProduct(Request $request): Response
{
        throw new ApiException(ErrorCode::FAIL, 'Invalid customer');
        return $this->response([]);
}
```

`config/exception`:
```
return [
//    '' => support\exception\Handler::class,
    '' => \support\exception\handler\ApiHandler::class
];
```

`support\exception\handler\ApiHandler`:
```
/**
 * Class Handler
 * @package support\exception
 */
class ApiHandler extends ExceptionHandler
{
    public $dontReport = [
        BusinessException::class,
    ];

    public $exceptionWhiteMap = [
        ApiException::class,
        ParamException::class,
    ];

    public function report(Throwable $exception)
    {
        parent::report($exception);
    }

    public function render(Request $request, Throwable $throwable): Response
    {
        $message = ErrorCode::getMessageByCode(ErrorCode::ServerError_FrameworkError);

        var_export(get_class($throwable)); //`'support\\exception\\ApiException'     'TypeError'`

        if (in_array(get_class($throwable), $this->exceptionWhiteMap)) {
            $message = $throwable->getMessage();
        } else {
            $log = [];
            $log['file'] = $throwable->getFile();
            $log['line'] = $throwable->getLine();
            $log['message'] = $throwable->getMessage();
            Log::channel('default')->info(json_encode($log, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        }

        $code = $throwable->getCode();
        $json = ['code' => $code, 'message' => $message];
        $this->_debug && $json['traces'] = (string)$throwable;
        return new Response(200, ['Content-Type' => 'application/json'], json_encode($json, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    }
}
```

**Comment by evilk123** [comment]
最奇怪的是
我抛出的是自定义异常,为啥最后handler还多接收到了另一个`TypeError`
这个`TypeError`是从限流包里抛出的
都没有触发限流机制,为啥限流包会抛出一个`TypeError`?
感觉没道理啊

**Comment by evilk123** [comment]
最后,我尝试修改限流包:
```
use support\{Container, Cache, Request};
use Webman\Http\Response;
use function sprintf;
```
就恢复正常了

但不解的还是
没有触发限流机制,为啥还会抛出一个`TypeError `?

**Comment by yuanzhihai** [comment]
> 最后,我尝试修改限流包:
> 
> ```
> use support\{Container, Cache, Request};
> use Webman\Http\Response;
> use function sprintf;
> ```
> 
> 就恢复正常了
> 
> 但不解的还是 没有触发限流机制,为啥还会抛出一个`TypeError `?

我修改依赖  Webman\Http\Response 吧
