### ISSUE TITLE
Class 'Symfony\Component\Cache\Adapter\RedisAdapter' not found in 

### ISSUE THREAD

**Issue by Amition** [yzh52521/webman-throttle#4]
D:\rj\phpstudy_pro\WWW\webman\vendor\workerman\webman-framework\src\support\Cache.php:35<br />
Stack trace:<br />
#0 D:\rj\phpstudy_pro\WWW\webman\vendor\workerman\webman-framework\src\support\Cache.php(48): support\Cache::instance()<br />
#1 D:\rj\phpstudy_pro\WWW\webman\vendor\yzh52521\webman-throttle\src\throttle\CounterFixed.php(16): support\Cache::__callStatic('get', Array)<br />
#2 D:\rj\phpstudy_pro\WWW\webman\vendor\yzh52521\webman-throttle\src\Throttle.php(110): yzh52521\middleware\throttle\CounterFixed->allowRequest('e21c67b8b16b538...', 1695698088.532, 3, 60, Object(support\Cache))<br />
#3 D:\rj\phpstudy_pro\WWW\webman\vendor\yzh52521\webman-throttle\src\Throttle.php(139): yzh52521\middleware\Throttle->allowRequest(Object(support\Request))<br />
#4 D:\rj\phpstudy_pro\WWW\webman\app\middleware\Throttle.php(24): yzh52521\middleware\Throttle->handle(Object(support\Request), Object(Closure), Array)<br />
#5 D:\rj\phpstudy_pro\WWW\webman\vendor\workerman\webman-framework\src\App.php(341): app\middleware\Throttle->process(Object(support\Request), Object(Closure))<br />
#6 D:\rj\phpstudy_pro\WWW\webman\vendor\workerman\webman-framework\src\App.php(141): Webman\App::Webman\{closure}(Object(support\Request))<br />
#7 D:\rj\phpstudy_pro\WWW\webman\vendor\workerman\workerman\Connection\TcpConnection.php(646): Webman\App->onMessage(Object(Workerman\Connection\TcpConnection), Object(support\Request))<br />
#8 D:\rj\phpstudy_pro\WWW\webman\vendor\workerman\workerman\Events\Select.php(311): Workerman\Connection\TcpConnection->baseRead(Resource id #243)<br />
#9 D:\rj\phpstudy_pro\WWW\webman\vendor\workerman\workerman\Worker.php(1485): Workerman\Events\Select->loop()<br />
#10 D:\rj\phpstudy_pro\WWW\webman\vendor\workerman\workerman\Worker.php(1402): Workerman\Worker::forkWorkersForWindows()<br />
#11 D:\rj\phpstudy_pro\WWW\webman\vendor\workerman\workerman\Worker.php(560): Workerman\Worker::forkWorkers()<br />
#12 D:\rj\phpstudy_pro\WWW\webman\vendor\workerman\webman-framework\src\support\App.php(131): Workerman\Worker::runAll()<br />
#13 D:\rj\phpstudy_pro\WWW\webman\start.php(4): support\App::run()<br />
#14 {main}

**Comment by yuanzhihai** [comment]
https://www.workerman.net/doc/webman/db/cache.html 
安装了么
